### ISSUE TITLE
Failed config on component

### ISSUE THREAD

**Issue by Rav3nholm** [johannesc/mspa-wifi#1]
Been trying to get this to work on my MSPA but have run into problems.
Don't know if its on my end the issue lies or something else.

Have a ESP32 S2 up and running with a base code but I cant get your code to work.
Get this error when validating:

`INFO ESPHome 2024.12.4
INFO Reading configuration /config/esphome/mspa.yaml...
ERROR Unable to load component mspa_wifi:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/esphome/components/mspa_wifi/__init__.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
Failed config

mspa_wifi: [source /config/esphome/mspa.yaml:59]
  
  Component not found: mspa_wifi.
  - id: mspa_wifi_1
    uart_box_to_remote_id: uart_box_to_remote
    uart_remote_to_box_id: uart_remote_to_box`

Am not used to components and Python in ESPhome so it could be that I have missed something.
I have installed this manually on in my HA environment and not through "PIP".

Would love to make this work and help you out in testing, have 2 MSPA hot tubs of different models that could be used in testing.

**Comment by johannesc** [comment]
If I am correct you are using "ESPHome Device Builder"? What is the content of the "mspa.yaml"? I think it should be something like:

```
esphome:
  name: mspa
  friendly_name: mspa

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/johannesc/mspa-wifi
      ref: main
    components: [ mspa_wifi ]

# Enable Home Assistant API
api:
  encryption:
    key: "7mG9m8ARKeQbY0guLEAdKAkG7wKczV9ZyJ0ubptmWds="

ota:
  - platform: esphome
    password: "3aa706a06ea65ef04185b9a23e787dc9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mspa Fallback Hotspot"
    password: "xbEwYsROJpuV"

captive_portal:


uart:
  - id: uart_box_to_remote
    rx_pin: # green cable to box
      number: GPIO33
      inverted: false
    tx_pin: # green cable to remote
      number: GPIO39
      inverted: false
    baud_rate: 9600
    rx_buffer_size: 512
  - id: uart_remote_to_box
    rx_pin: # black cable to remote
      number: GPIO37
      inverted: false
    tx_pin: # black cable to box
      number: GPIO18
      inverted: false
    baud_rate: 9600
    rx_buffer_size: 512

mspa_wifi:
  - id: mspa_wifi_1
    uart_box_to_remote_id: uart_box_to_remote
    uart_remote_to_box_id: uart_remote_to_box

binary_sensor:
  - platform: mspa_wifi
    flow_in:
      name: "Flow In"
    flow_out:
      name: "Flow Out"
    filter_pump:
      name: "Filter Pump"
    uvc:
      name: "UVC"
    ozone:
      name: "Ozone"
    heater:
      name: "Heater"

sensor:
  - platform: mspa_wifi
    water_temperature:
      name: "Temperature"
  - platform: mspa_wifi
    target_water_temperature:
      name: "Target Temperature"
      on_value:
      - lambda: |-
          id(target_water_temp).publish_state(x);
  - platform: mspa_wifi
    bubble_speed:
      name: "Bubble Speed"
      on_value:
      - lambda: |-
          id(target_bubble_speed).publish_state(x);
number:
  - platform: template
    name: "Target water temp"
    id: target_water_temp
    min_value: 24
    max_value: 40
    step: 1
    icon: "mdi:thermometer"
    optimistic: true
    restore_value: false
    set_action:
      - lambda: |-
          ESP_LOGI("number_template", "New value from HA: %f", x);
          id(mspa_wifi_1)->set_target_water_temperature(x);
  - platform: template
    name: "Bubble Speed"
    id: target_bubble_speed
    min_value: 0
    max_value: 3
    step: 1
    optimistic: false
    restore_value: false
    set_action:
      - lambda: |-
          ESP_LOGI("bubble speed template", "New value from HA: %f", x);
          id(mspa_wifi_1)->set_bubble_speed((uint8_t)x);

```

**Comment by Rav3nholm** [comment]
This is my mspa.yaml

```yaml
esphome:
  name: mspa
  friendly_name: MSPA

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO  # Set to DEBUG if you are having issues!


api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mspa Fallback Hotspot"
    password: "xxx"

captive_portal:

external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/johannesc/mspa-wifi
      ref: main
    components: [ mspa_wifi ]

uart:
  - id: uart_box_to_remote
    rx_pin: # green cable to box
      number: GPIO33
      inverted: false
    tx_pin: # green cable to remote
      number: GPIO39
      inverted: false
    baud_rate: 9600
    rx_buffer_size: 512
  - id: uart_remote_to_box
    rx_pin: # black cable to remote
      number: GPIO37
      inverted: false
    tx_pin: # black cable to box
      number: GPIO18
      inverted: false
    baud_rate: 9600
    rx_buffer_size: 512

mspa_wifi:
  - id: mspa_wifi_1
    uart_box_to_remote_id: uart_box_to_remote
    uart_remote_to_box_id: uart_remote_to_box

binary_sensor:
  - platform: mspa_wifi
    flow_in:
      name: "Flow In"
    flow_out:
      name: "Flow Out"
    filter_pump:
      name: "Filter Pump"
    uvc:
      name: "UVC"
    ozone:
      name: "Ozone"
    heater:
      name: "Heater"

sensor:
  - platform: mspa_wifi
    water_temperature:
      name: "Temperature"
  - platform: mspa_wifi
    target_water_temperature:
      name: "Target Temperature"
      on_value:
      - lambda: |-
          id(target_water_temp).publish_state(x);
  - platform: mspa_wifi
    bubble_speed:
      name: "Bubble Speed"
      on_value:
      - lambda: |-
          id(target_bubble_speed).publish_state(x);
number:
  - platform: template
    name: "Target water temp"
    id: target_water_temp
    min_value: 24
    max_value: 40
    step: 1
    icon: "mdi:thermometer"
    optimistic: true
    restore_value: false
    set_action:
      - lambda: |-
          ESP_LOGI("number_template", "New value from HA: %f", x);
          id(mspa_wifi_1)->set_target_water_temperature(x);
  - platform: template
    name: "Bubble Speed"
    id: target_bubble_speed
    min_value: 0
    max_value: 3
    step: 1
    optimistic: false
    restore_value: false
    set_action:
      - lambda: |-
          ESP_LOGI("bubble speed template", "New value from HA: %f", x);
          id(mspa_wifi_1)->set_bubble_speed((uint8_t)x);
```
Now after I modified the component part of my code it does validate and writes to my ESP32 so that great!
I havent tried it on my SPA yet, will do that later this week or weekend.
Reporting back on the results then!
